

services:
  necotemplate.api:
    image: ${DOCKER_REGISTRY-}necotemplateapi
    container_name: necotemplate-api
    build:
      context: .
      dockerfile: NecoTemplate/Dockerfile
    depends_on:
      - necotemplate-redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:8080"
      - "5001:8081"
  necotemplate-db:
    image: postgres:15
    container_name: necotemplate-Db
    environment:
      - POSTGRES_DB=testE1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  necotemplate-redis:
    image: redis:latest
    container_name: necotemplate-Redis
    restart: always
    ports:
      - "6379:6379"
  elasticsearch:
    image: elasticsearch:8.18.2
    container_name: necotemplate-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=123456
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
  logstash:
    image: logstash:8.18.2
    ports:
      - "8080:8080"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:8.18.2
    environment:
       ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
       ELASTICSEARCH_USERNAME: "kibana_system"
       ELASTICSEARCH_PASSWORD: "1YmSN42ntl31Ugq49ZEH"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

 

volumes:
  pgdata:
  esdata:


